Loaded module: cuda/11.8
ERROR: Unable to locate a modulefile for 'python3/3.9.18'
WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /zhome/4e/b/208805/.local/lib/python3.9/site-packages
sysconfig: /zhome/4e/b/208805/.local/lib64/python3.9/site-packages
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
Traceback (most recent call last):
  File "/dtu/p1/johlau/Thesis-Synthex/imageng-drr.py", line 20, in <module>
    patient = deepdrr.Volume.from_nifti(
  File "/zhome/4e/b/208805/.local/lib/python3.9/site-packages/deepdrr/vol/volume.py", line 486, in from_nifti
    img = nib.load(path)
  File "/zhome/4e/b/208805/.local/lib/python3.9/site-packages/nibabel/loadsave.py", line 55, in load
    raise ImageFileError(f'Cannot work out file type of "{filename}"')
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/dtu/p1/johlau/Thesis-Synthex/data/ImagEng-NIFTI/cache"
