Loaded module: cuda/11.8
ERROR: Unable to locate a modulefile for 'python3/3.9.18'
  WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /zhome/4e/b/208805/.local/lib/python3.9/site-packages
  sysconfig: /zhome/4e/b/208805/.local/lib64/python3.9/site-packages
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None
  WARNING: The scripts py.test and pytest are installed in '/zhome/4e/b/208805/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts black and blackd are installed in '/zhome/4e/b/208805/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Traceback (most recent call last):
  File "/dtu/p1/johlau/Thesis-Synthex/imageng-drr.py", line 20, in <module>
    patient = deepdrr.Volume.from_nifti(
  File "/zhome/4e/b/208805/.local/lib/python3.9/site-packages/deepdrr/vol/volume.py", line 528, in from_nifti
    return cls(
  File "/zhome/4e/b/208805/.local/lib/python3.9/site-packages/deepdrr/vol/volume.py", line 69, in __init__
    self.data = np.array(data).astype(np.float32)
KeyboardInterrupt
Terminated
