Loaded module: cuda/12.2
/dtu/p1/johlau/Thesis-Synthex/.venv/lib/python3.9/site-packages/keras/src/layers/layer.py:360: UserWarning: `build()` was called on layer 'patch_encoder', however the layer does not have a `build()` method implemented and it looks like it has unbuilt state. This will cause the layer to be marked as built, despite not being actually built, which may cause failures down the line. Make sure to implement a proper `build()` method.
  warnings.warn(
0it [00:00, ?it/s]0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/dtu/p1/johlau/Thesis-Synthex/object_detection/crop_padchest.py", line 56, in <module>
    cropped_image = crop_augment(image,model, original_image_size=image.size )
  File "/dtu/p1/johlau/Thesis-Synthex/object_detection/crop_padchest.py", line 26, in crop_augment
    preds = model.predict(np.expand_dims(keras.utils.img_to_array(image), axis=0))[0]
  File "/dtu/p1/johlau/Thesis-Synthex/.venv/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/dtu/p1/johlau/Thesis-Synthex/object_detection/VisionTransformer.py", line 124, in call
    projected_patches = self.projection(patch)
ValueError: Exception encountered when calling PatchEncoder.call().

[1mInput 0 of layer "dense" is incompatible with the layer: expected axis -1 of input shape to have value 12288, but received input with shape (1, 9, 4096)[0m

Arguments received by PatchEncoder.call():
  â€¢ patch=jnp.ndarray(shape=(1, 9, 4096), dtype=float32)
