Loaded module: cuda/12.2
WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /zhome/4e/b/208805/.local/lib/python3.9/site-packages
sysconfig: /zhome/4e/b/208805/.local/lib64/python3.9/site-packages
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
  WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /zhome/4e/b/208805/.local/lib/python3.9/site-packages
  sysconfig: /zhome/4e/b/208805/.local/lib64/python3.9/site-packages
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None
  WARNING: The script unidecode is installed in '/zhome/4e/b/208805/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Traceback (most recent call last):
  File "/dtu/p1/johlau/Thesis-Synthex/nbia_downloader.py", line 4, in <module>
    from tcia_utils import nbia
  File "/zhome/4e/b/208805/.local/lib/python3.9/site-packages/tcia_utils/__init__.py", line 1, in <module>
    from . import nbia
  File "/zhome/4e/b/208805/.local/lib/python3.9/site-packages/tcia_utils/nbia.py", line 22, in <module>
    from tcia_utils.utils import searchDf
  File "/zhome/4e/b/208805/.local/lib/python3.9/site-packages/tcia_utils/utils.py", line 3, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
